// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taskFieldNames          = builder.RawFieldNames(&Task{})
	taskRows                = strings.Join(taskFieldNames, ",")
	taskRowsExpectAutoSet   = strings.Join(stringx.Remove(taskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	taskRowsWithPlaceHolder = strings.Join(stringx.Remove(taskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGtodolistTaskIdPrefix = "cache:gtodolist:task:id:"
)

type (
	taskModel interface {
		Insert(ctx context.Context, data *Task) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Task, error)
		Update(ctx context.Context, data *Task) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTaskModel struct {
		sqlc.CachedConn
		table string
	}

	Task struct {
		Id        int64          `db:"id"`         // 主键
		CreatedAt time.Time      `db:"created_at"` // 创建时间
		UpdatedAt time.Time      `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime   `db:"deleted_at"` // 删除时间
		Uid       int64          `db:"uid"`        // 用户id
		Title     string         `db:"title"`      // 任务标题
		Status    int64          `db:"status"`     // 任务状态 0代办 1已完成
		Content   sql.NullString `db:"content"`    // 任务内容
		StartTime time.Time      `db:"start_time"` // 任务开始时间
		EndTime   sql.NullTime   `db:"end_time"`   // 任务结束时间
	}
)

func newTaskModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTaskModel {
	return &defaultTaskModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`task`",
	}
}

func (m *defaultTaskModel) withSession(session sqlx.Session) *defaultTaskModel {
	return &defaultTaskModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`task`",
	}
}

func (m *defaultTaskModel) Delete(ctx context.Context, id int64) error {
	gtodolistTaskIdKey := fmt.Sprintf("%s%v", cacheGtodolistTaskIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, gtodolistTaskIdKey)
	return err
}

func (m *defaultTaskModel) FindOne(ctx context.Context, id int64) (*Task, error) {
	gtodolistTaskIdKey := fmt.Sprintf("%s%v", cacheGtodolistTaskIdPrefix, id)
	var resp Task
	err := m.QueryRowCtx(ctx, &resp, gtodolistTaskIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taskRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskModel) Insert(ctx context.Context, data *Task) (sql.Result, error) {
	gtodolistTaskIdKey := fmt.Sprintf("%s%v", cacheGtodolistTaskIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, taskRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.Uid, data.Title, data.Status, data.Content, data.StartTime, data.EndTime)
	}, gtodolistTaskIdKey)
	return ret, err
}

func (m *defaultTaskModel) Update(ctx context.Context, data *Task) error {
	gtodolistTaskIdKey := fmt.Sprintf("%s%v", cacheGtodolistTaskIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, taskRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.Uid, data.Title, data.Status, data.Content, data.StartTime, data.EndTime, data.Id)
	}, gtodolistTaskIdKey)
	return err
}

func (m *defaultTaskModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGtodolistTaskIdPrefix, primary)
}

func (m *defaultTaskModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taskRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTaskModel) tableName() string {
	return m.table
}
