// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"gtodolist/app/task/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/task_create",
				Handler: TaskCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/task_list",
				Handler: TaskListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/task_show",
				Handler: TaskShowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/task_update",
				Handler: TaskUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/task_search",
				Handler: TaskSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/task_delete",
				Handler: TaskDeleteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
