// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"gtodolist/app/user/cmd/rpc/internal/logic"
	"gtodolist/app/user/cmd/rpc/internal/svc"
	"gtodolist/app/user/cmd/rpc/pb"
)

type UerrpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUerrpcServer
}

func NewUerrpcServer(svcCtx *svc.ServiceContext) *UerrpcServer {
	return &UerrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UerrpcServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UerrpcServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
