# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        go mod tidy 
        mkdir tmp
        go build -o ./temp/user-api ./app/user/cmd/api/user.go
        go build -o ./temp/user-rpc ./app/user/cmd/rpc/user.go
    
    - name: Deploy To Server
      uses: hengkx/ssh-deploy@v1.0.1
      with:
        HOST: ${{ secrets.HOST }} 
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PORT: ${{ secrets.PORT }}
        SOURCE: ./temp
        TARGET: /home/guochenxu/gtodolist/go/temp
        AFTER_COMMAND: |
          cd /home/guochenxu/gtodolist/go
          ./start.sh
    
