# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    # 设置容器环境
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

#    # 设置 GO 版本
#    - name: Set up Go
#      uses: actions/setup-go@v4
#      with:
#        go-version: '1.20'

#    # 编译
#    - name: Build
#      run: |
#        go mod tidy
#        mkdir tmp
#        go build -o ./cmd/user-api ./app/user/cmd/api/user.go
#        go build -o ./cmd/user-rpc ./app/user/cmd/rpc/user.go
#        go build -o ./cmd/task-api ./app/task/cmd/api/task.go
#        go build -o ./cmd/task-rpc ./app/task/cmd/rpc/task.go
#        tar -zcvf ./cmd.tar.gz ./cmd

#    # 使用 scp 把文件传输到服务器上
#    - name: Transfer to server
#      uses: appleboy/scp-action@v0.1.4
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
#        port: ${{ secrets.PORT }}
#        source: "./cmd.tar.gz"
#        target: /home/guochenxu/gtodolist/go/

    # 使用 rsync 把文件传输到服务器上
    - name: Transfer to server
      uses: up9cloud/action-rsync@master
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD:  ${{ secrets.PASSWORD }}

        TARGET: /home/guochenxu/gtodolist/go/gtodolist
        SOURCE: ./
        ARGS: -avuz --progress --delete --exclude=./.git/

        PRE_SCRIPT: |
          echo start at:
          date -u
        POST_SCRIPT: "echo done at: && date -u"

    # 远程执行命令
    - name: Run Service On Server
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: |
          cd /home/guochenxu/gtodolist/go
          ./start.sh
          logout
