// Code generated by goctl. DO NOT EDIT.
// Source: task.proto

package server

import (
	"context"

	"gtodolist/app/task/cmd/rpc/internal/logic"
	"gtodolist/app/task/cmd/rpc/internal/svc"
	"gtodolist/app/task/cmd/rpc/pb"
)

type TaskrpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTaskrpcServer
}

func NewTaskrpcServer(svcCtx *svc.ServiceContext) *TaskrpcServer {
	return &TaskrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskrpcServer) CreateTask(ctx context.Context, in *pb.CreateReq) (*pb.CreateResp, error) {
	l := logic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}

func (s *TaskrpcServer) ListTask(ctx context.Context, in *pb.ListReq) (*pb.ListResp, error) {
	l := logic.NewListTaskLogic(ctx, s.svcCtx)
	return l.ListTask(in)
}

func (s *TaskrpcServer) ShowTask(ctx context.Context, in *pb.ShowReq) (*pb.ShowResp, error) {
	l := logic.NewShowTaskLogic(ctx, s.svcCtx)
	return l.ShowTask(in)
}

func (s *TaskrpcServer) UpdateTask(ctx context.Context, in *pb.UpdateReq) (*pb.UpdateResp, error) {
	l := logic.NewUpdateTaskLogic(ctx, s.svcCtx)
	return l.UpdateTask(in)
}

func (s *TaskrpcServer) SearchTask(ctx context.Context, in *pb.SearchReq) (*pb.SearchResp, error) {
	l := logic.NewSearchTaskLogic(ctx, s.svcCtx)
	return l.SearchTask(in)
}

func (s *TaskrpcServer) DeleteTask(ctx context.Context, in *pb.DeleteReq) (*pb.DeleteResp, error) {
	l := logic.NewDeleteTaskLogic(ctx, s.svcCtx)
	return l.DeleteTask(in)
}
